// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserWalletRequest) Reset() {
	*x = CreateUserWalletRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserWalletRequest) ProtoMessage() {}

func (x *CreateUserWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateUserWalletRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateChannelWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelWalletRequest) Reset() {
	*x = CreateChannelWalletRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelWalletRequest) ProtoMessage() {}

func (x *CreateChannelWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelWalletRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChannelWalletRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRequest) Reset() {
	*x = ChannelRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRequest) ProtoMessage() {}

func (x *ChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRequest.ProtoReflect.Descriptor instead.
func (*ChannelRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatingRequest) Reset() {
	*x = GatingRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatingRequest) ProtoMessage() {}

func (x *GatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatingRequest.ProtoReflect.Descriptor instead.
func (*GatingRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GatingRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GatingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_transaction_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscriptionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`  // 0x... EVM address (42 chars: "0x" + 40 hex)
	Existed       bool                   `protobuf:"varint,2,opt,name=existed,proto3" json:"existed,omitempty"` // true = кошелёк уже был, false = создан в этом вызове
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *WalletResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type BalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SudaBalanceWei string                 `protobuf:"bytes,1,opt,name=suda_balance_wei,json=sudaBalanceWei,proto3" json:"suda_balance_wei,omitempty"` // uint256 как строка (wei, 18 decimals)
	Decimals       int32                  `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`                                    // всегда 18 для SUDA
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                       // адрес для удобства логирования/дебага
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceResponse) GetSudaBalanceWei() string {
	if x != nil {
		return x.SudaBalanceWei
	}
	return ""
}

func (x *BalanceResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *BalanceResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GatingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Required       bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	Passed         bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	MinBalanceWei  string                 `protobuf:"bytes,3,opt,name=min_balance_wei,json=minBalanceWei,proto3" json:"min_balance_wei,omitempty"`
	UserBalanceWei string                 `protobuf:"bytes,4,opt,name=user_balance_wei,json=userBalanceWei,proto3" json:"user_balance_wei,omitempty"`
	// reason values:
	//
	//	"ok"                    — required=false ИЛИ passed=true
	//	"no_wallet"             — у юзера нет кошелька (не зарегистрирован в Transaction)
	//	"insufficient_balance"  — баланса не хватает
	//	"nft_required"          — нужен NFT из коллекции, его нет
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	PriceWei      string `protobuf:"bytes,6,opt,name=price_wei,json=priceWei,proto3" json:"price_wei,omitempty"` // цена платной подписки в wei ("0" = не платный)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatingResponse) Reset() {
	*x = GatingResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatingResponse) ProtoMessage() {}

func (x *GatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatingResponse.ProtoReflect.Descriptor instead.
func (*GatingResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *GatingResponse) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *GatingResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *GatingResponse) GetMinBalanceWei() string {
	if x != nil {
		return x.MinBalanceWei
	}
	return ""
}

func (x *GatingResponse) GetUserBalanceWei() string {
	if x != nil {
		return x.UserBalanceWei
	}
	return ""
}

func (x *GatingResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GatingResponse) GetPriceWei() string {
	if x != nil {
		return x.PriceWei
	}
	return ""
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`       // hash транзакции списания (async-подтверждение через observer)
	PriceWei      string                 `protobuf:"bytes,2,opt,name=price_wei,json=priceWei,proto3" json:"price_wei,omitempty"` // списанная цена в wei
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_transaction_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SubscriptionResponse) GetPriceWei() string {
	if x != nil {
		return x.PriceWei
	}
	return ""
}

var File_transaction_transaction_proto protoreflect.FileDescriptor

const file_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1dtransaction/transaction.proto\x12\vtransaction\"2\n" +
	"\x17CreateUserWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x1aCreateChannelWalletRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x0eChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"A\n" +
	"\rGatingRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\x13SubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"D\n" +
	"\x0eWalletResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\aexisted\x18\x02 \x01(\bR\aexisted\"q\n" +
	"\x0fBalanceResponse\x12(\n" +
	"\x10suda_balance_wei\x18\x01 \x01(\tR\x0esudaBalanceWei\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\x05R\bdecimals\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xcb\x01\n" +
	"\x0eGatingResponse\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12&\n" +
	"\x0fmin_balance_wei\x18\x03 \x01(\tR\rminBalanceWei\x12(\n" +
	"\x10user_balance_wei\x18\x04 \x01(\tR\x0euserBalanceWei\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1b\n" +
	"\tprice_wei\x18\x06 \x01(\tR\bpriceWei\"L\n" +
	"\x14SubscriptionResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tprice_wei\x18\x02 \x01(\tR\bpriceWei2\xd5\x04\n" +
	"\x12TransactionService\x12X\n" +
	"\x13CreateWalletForUser\x12$.transaction.CreateUserWalletRequest\x1a\x1b.transaction.WalletResponse\x12^\n" +
	"\x16CreateWalletForChannel\x12'.transaction.CreateChannelWalletRequest\x1a\x1b.transaction.WalletResponse\x12B\n" +
	"\tGetWallet\x12\x18.transaction.UserRequest\x1a\x1b.transaction.WalletResponse\x12L\n" +
	"\x10GetChannelWallet\x12\x1b.transaction.ChannelRequest\x1a\x1b.transaction.WalletResponse\x12D\n" +
	"\n" +
	"GetBalance\x12\x18.transaction.UserRequest\x1a\x1c.transaction.BalanceResponse\x12K\n" +
	"\x10CheckTokenGating\x12\x1a.transaction.GatingRequest\x1a\x1b.transaction.GatingResponse\x12`\n" +
	"\x19ChargeChannelSubscription\x12 .transaction.SubscriptionRequest\x1a!.transaction.SubscriptionResponseBEZCgithub.com/moera-sudo/backend/backend/proto/transaction;transactionb\x06proto3"

var (
	file_transaction_transaction_proto_rawDescOnce sync.Once
	file_transaction_transaction_proto_rawDescData []byte
)

func file_transaction_transaction_proto_rawDescGZIP() []byte {
	file_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)))
	})
	return file_transaction_transaction_proto_rawDescData
}

var file_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_transaction_transaction_proto_goTypes = []any{
	(*CreateUserWalletRequest)(nil),    // 0: transaction.CreateUserWalletRequest
	(*CreateChannelWalletRequest)(nil), // 1: transaction.CreateChannelWalletRequest
	(*UserRequest)(nil),                // 2: transaction.UserRequest
	(*ChannelRequest)(nil),             // 3: transaction.ChannelRequest
	(*GatingRequest)(nil),              // 4: transaction.GatingRequest
	(*SubscriptionRequest)(nil),        // 5: transaction.SubscriptionRequest
	(*WalletResponse)(nil),             // 6: transaction.WalletResponse
	(*BalanceResponse)(nil),            // 7: transaction.BalanceResponse
	(*GatingResponse)(nil),             // 8: transaction.GatingResponse
	(*SubscriptionResponse)(nil),       // 9: transaction.SubscriptionResponse
}
var file_transaction_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.CreateWalletForUser:input_type -> transaction.CreateUserWalletRequest
	1, // 1: transaction.TransactionService.CreateWalletForChannel:input_type -> transaction.CreateChannelWalletRequest
	2, // 2: transaction.TransactionService.GetWallet:input_type -> transaction.UserRequest
	3, // 3: transaction.TransactionService.GetChannelWallet:input_type -> transaction.ChannelRequest
	2, // 4: transaction.TransactionService.GetBalance:input_type -> transaction.UserRequest
	4, // 5: transaction.TransactionService.CheckTokenGating:input_type -> transaction.GatingRequest
	5, // 6: transaction.TransactionService.ChargeChannelSubscription:input_type -> transaction.SubscriptionRequest
	6, // 7: transaction.TransactionService.CreateWalletForUser:output_type -> transaction.WalletResponse
	6, // 8: transaction.TransactionService.CreateWalletForChannel:output_type -> transaction.WalletResponse
	6, // 9: transaction.TransactionService.GetWallet:output_type -> transaction.WalletResponse
	6, // 10: transaction.TransactionService.GetChannelWallet:output_type -> transaction.WalletResponse
	7, // 11: transaction.TransactionService.GetBalance:output_type -> transaction.BalanceResponse
	8, // 12: transaction.TransactionService.CheckTokenGating:output_type -> transaction.GatingResponse
	9, // 13: transaction.TransactionService.ChargeChannelSubscription:output_type -> transaction.SubscriptionResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_transaction_proto_init() }
func file_transaction_transaction_proto_init() {
	if File_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_proto_rawDesc), len(file_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_transaction_proto_msgTypes,
	}.Build()
	File_transaction_transaction_proto = out.File
	file_transaction_transaction_proto_goTypes = nil
	file_transaction_transaction_proto_depIdxs = nil
}
