// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: transaction/transaction.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_CreateWalletForUser_FullMethodName       = "/transaction.TransactionService/CreateWalletForUser"
	TransactionService_CreateWalletForChannel_FullMethodName    = "/transaction.TransactionService/CreateWalletForChannel"
	TransactionService_GetWallet_FullMethodName                 = "/transaction.TransactionService/GetWallet"
	TransactionService_GetChannelWallet_FullMethodName          = "/transaction.TransactionService/GetChannelWallet"
	TransactionService_GetBalance_FullMethodName                = "/transaction.TransactionService/GetBalance"
	TransactionService_CheckTokenGating_FullMethodName          = "/transaction.TransactionService/CheckTokenGating"
	TransactionService_ChargeChannelSubscription_FullMethodName = "/transaction.TransactionService/ChargeChannelSubscription"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	// Создать кастодиальный кошелёк для юзера. Идемпотентен:
	// если уже есть — вернёт существующий address и existed=true.
	CreateWalletForUser(ctx context.Context, in *CreateUserWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	// Создать кастодиальный кошелёк для канала (treasury).
	// Идемпотентен. Адрес используется как to-адрес для донатов канала
	// и как from-адрес при создании квестов/сборов от имени канала.
	CreateWalletForChannel(ctx context.Context, in *CreateChannelWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	// Получить адрес кошелька юзера (из БД, без RPC к Besu).
	GetWallet(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	// Получить адрес кошелька канала.
	GetChannelWallet(ctx context.Context, in *ChannelRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	// Получить on-chain баланс SUDA у юзера.
	// Делает SudaToken.balanceOf() на Besu, обновляет кеш в Postgres.
	GetBalance(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	// Проверить правило токен-гейтинга для чата/канала.
	//
	//	required=false  → правила нет, пропускаем.
	//	required=true,  passed=true   → юзер проходит.
	//	required=true,  passed=false  → юзер не проходит, reason указывает причину.
	//	price_wei       → цена платной подписки (если канал платный), "0" иначе.
	CheckTokenGating(ctx context.Context, in *GatingRequest, opts ...grpc.CallOption) (*GatingResponse, error)
	// Списать с юзера цену платной подписки на PUBLIC-канал в treasury канала.
	// Вызывается Messenger.channel.Subscribe для платного канала ДО AddMember.
	// Ошибка, если у канала нет правила с ценой > 0 (не платный канал).
	ChargeChannelSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) CreateWalletForUser(ctx context.Context, in *CreateUserWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreateWalletForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CreateWalletForChannel(ctx context.Context, in *CreateChannelWalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, TransactionService_CreateWalletForChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetWallet(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetChannelWallet(ctx context.Context, in *ChannelRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetChannelWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetBalance(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) CheckTokenGating(ctx context.Context, in *GatingRequest, opts ...grpc.CallOption) (*GatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatingResponse)
	err := c.cc.Invoke(ctx, TransactionService_CheckTokenGating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ChargeChannelSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, TransactionService_ChargeChannelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
type TransactionServiceServer interface {
	// Создать кастодиальный кошелёк для юзера. Идемпотентен:
	// если уже есть — вернёт существующий address и existed=true.
	CreateWalletForUser(context.Context, *CreateUserWalletRequest) (*WalletResponse, error)
	// Создать кастодиальный кошелёк для канала (treasury).
	// Идемпотентен. Адрес используется как to-адрес для донатов канала
	// и как from-адрес при создании квестов/сборов от имени канала.
	CreateWalletForChannel(context.Context, *CreateChannelWalletRequest) (*WalletResponse, error)
	// Получить адрес кошелька юзера (из БД, без RPC к Besu).
	GetWallet(context.Context, *UserRequest) (*WalletResponse, error)
	// Получить адрес кошелька канала.
	GetChannelWallet(context.Context, *ChannelRequest) (*WalletResponse, error)
	// Получить on-chain баланс SUDA у юзера.
	// Делает SudaToken.balanceOf() на Besu, обновляет кеш в Postgres.
	GetBalance(context.Context, *UserRequest) (*BalanceResponse, error)
	// Проверить правило токен-гейтинга для чата/канала.
	//
	//	required=false  → правила нет, пропускаем.
	//	required=true,  passed=true   → юзер проходит.
	//	required=true,  passed=false  → юзер не проходит, reason указывает причину.
	//	price_wei       → цена платной подписки (если канал платный), "0" иначе.
	CheckTokenGating(context.Context, *GatingRequest) (*GatingResponse, error)
	// Списать с юзера цену платной подписки на PUBLIC-канал в treasury канала.
	// Вызывается Messenger.channel.Subscribe для платного канала ДО AddMember.
	// Ошибка, если у канала нет правила с ценой > 0 (не платный канал).
	ChargeChannelSubscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) CreateWalletForUser(context.Context, *CreateUserWalletRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWalletForUser not implemented")
}
func (UnimplementedTransactionServiceServer) CreateWalletForChannel(context.Context, *CreateChannelWalletRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWalletForChannel not implemented")
}
func (UnimplementedTransactionServiceServer) GetWallet(context.Context, *UserRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedTransactionServiceServer) GetChannelWallet(context.Context, *ChannelRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChannelWallet not implemented")
}
func (UnimplementedTransactionServiceServer) GetBalance(context.Context, *UserRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedTransactionServiceServer) CheckTokenGating(context.Context, *GatingRequest) (*GatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTokenGating not implemented")
}
func (UnimplementedTransactionServiceServer) ChargeChannelSubscription(context.Context, *SubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChargeChannelSubscription not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_CreateWalletForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateWalletForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreateWalletForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateWalletForUser(ctx, req.(*CreateUserWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CreateWalletForChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateWalletForChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CreateWalletForChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateWalletForChannel(ctx, req.(*CreateChannelWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetWallet(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetChannelWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetChannelWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetChannelWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetChannelWallet(ctx, req.(*ChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetBalance(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_CheckTokenGating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CheckTokenGating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_CheckTokenGating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CheckTokenGating(ctx, req.(*GatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ChargeChannelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ChargeChannelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ChargeChannelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ChargeChannelSubscription(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWalletForUser",
			Handler:    _TransactionService_CreateWalletForUser_Handler,
		},
		{
			MethodName: "CreateWalletForChannel",
			Handler:    _TransactionService_CreateWalletForChannel_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _TransactionService_GetWallet_Handler,
		},
		{
			MethodName: "GetChannelWallet",
			Handler:    _TransactionService_GetChannelWallet_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _TransactionService_GetBalance_Handler,
		},
		{
			MethodName: "CheckTokenGating",
			Handler:    _TransactionService_CheckTokenGating_Handler,
		},
		{
			MethodName: "ChargeChannelSubscription",
			Handler:    _TransactionService_ChargeChannelSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}
