// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: media/media.proto

package media

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_GetMedia_FullMethodName          = "/media.MediaService/GetMedia"
	MediaService_LinkMediaToEntity_FullMethodName = "/media.MediaService/LinkMediaToEntity"
	MediaService_BatchGetMediaURLs_FullMethodName = "/media.MediaService/BatchGetMediaURLs"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===================================================
// Media Service gRPC API
// Используется другими микросервисами для работы с медиа.
//
// Примеры использования:
//   - messenger-service вызывает LinkMediaToEntity при отправке сообщения с вложением
//   - messenger-service вызывает BatchGetMediaURLs при загрузке списка сообщений
//   - api-gateway может вызвать GetMedia для проверки статуса
//
// ===================================================
type MediaServiceClient interface {
	// Получить метаданные медиа по ID
	GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*GetMediaResponse, error)
	// Привязать медиа к сущности (вызывается messenger-service при отправке сообщения)
	LinkMediaToEntity(ctx context.Context, in *LinkMediaToEntityRequest, opts ...grpc.CallOption) (*LinkMediaToEntityResponse, error)
	// Пакетное получение URL для нескольких медиа (для списка сообщений в чате)
	BatchGetMediaURLs(ctx context.Context, in *BatchGetMediaURLsRequest, opts ...grpc.CallOption) (*BatchGetMediaURLsResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*GetMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaResponse)
	err := c.cc.Invoke(ctx, MediaService_GetMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) LinkMediaToEntity(ctx context.Context, in *LinkMediaToEntityRequest, opts ...grpc.CallOption) (*LinkMediaToEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkMediaToEntityResponse)
	err := c.cc.Invoke(ctx, MediaService_LinkMediaToEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) BatchGetMediaURLs(ctx context.Context, in *BatchGetMediaURLsRequest, opts ...grpc.CallOption) (*BatchGetMediaURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetMediaURLsResponse)
	err := c.cc.Invoke(ctx, MediaService_BatchGetMediaURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
//
// ===================================================
// Media Service gRPC API
// Используется другими микросервисами для работы с медиа.
//
// Примеры использования:
//   - messenger-service вызывает LinkMediaToEntity при отправке сообщения с вложением
//   - messenger-service вызывает BatchGetMediaURLs при загрузке списка сообщений
//   - api-gateway может вызвать GetMedia для проверки статуса
//
// ===================================================
type MediaServiceServer interface {
	// Получить метаданные медиа по ID
	GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error)
	// Привязать медиа к сущности (вызывается messenger-service при отправке сообщения)
	LinkMediaToEntity(context.Context, *LinkMediaToEntityRequest) (*LinkMediaToEntityResponse, error)
	// Пакетное получение URL для нескольких медиа (для списка сообщений в чате)
	BatchGetMediaURLs(context.Context, *BatchGetMediaURLsRequest) (*BatchGetMediaURLsResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedMediaServiceServer) LinkMediaToEntity(context.Context, *LinkMediaToEntityRequest) (*LinkMediaToEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkMediaToEntity not implemented")
}
func (UnimplementedMediaServiceServer) BatchGetMediaURLs(context.Context, *BatchGetMediaURLsRequest) (*BatchGetMediaURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetMediaURLs not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_GetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMedia(ctx, req.(*GetMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_LinkMediaToEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkMediaToEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).LinkMediaToEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_LinkMediaToEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).LinkMediaToEntity(ctx, req.(*LinkMediaToEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_BatchGetMediaURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetMediaURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).BatchGetMediaURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_BatchGetMediaURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).BatchGetMediaURLs(ctx, req.(*BatchGetMediaURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMedia",
			Handler:    _MediaService_GetMedia_Handler,
		},
		{
			MethodName: "LinkMediaToEntity",
			Handler:    _MediaService_LinkMediaToEntity_Handler,
		},
		{
			MethodName: "BatchGetMediaURLs",
			Handler:    _MediaService_BatchGetMediaURLs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media/media.proto",
}
