// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: media/media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetMediaResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                                  // AVATAR, ATTACHMENT, VOICE_MESSAGE ...
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // image/jpeg, audio/ogg ...
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // PENDING, READY, DELETED
	IsPrivate     bool                   `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	OriginalName  string                 `protobuf:"bytes,8,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *MediaInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaInfo) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *MediaInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MediaInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *MediaInfo) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *MediaInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LinkMediaToEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // MESSAGE, CHAT_AVATAR, USER_AVATAR
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // message_id, chat_id, user_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkMediaToEntityRequest) Reset() {
	*x = LinkMediaToEntityRequest{}
	mi := &file_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkMediaToEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkMediaToEntityRequest) ProtoMessage() {}

func (x *LinkMediaToEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkMediaToEntityRequest.ProtoReflect.Descriptor instead.
func (*LinkMediaToEntityRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *LinkMediaToEntityRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *LinkMediaToEntityRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *LinkMediaToEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type LinkMediaToEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkMediaToEntityResponse) Reset() {
	*x = LinkMediaToEntityResponse{}
	mi := &file_media_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkMediaToEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkMediaToEntityResponse) ProtoMessage() {}

func (x *LinkMediaToEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkMediaToEntityResponse.ProtoReflect.Descriptor instead.
func (*LinkMediaToEntityResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{4}
}

func (x *LinkMediaToEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BatchGetMediaURLsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaIds        []string               `protobuf:"bytes,1,rep,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchGetMediaURLsRequest) Reset() {
	*x = BatchGetMediaURLsRequest{}
	mi := &file_media_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMediaURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMediaURLsRequest) ProtoMessage() {}

func (x *BatchGetMediaURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMediaURLsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetMediaURLsRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetMediaURLsRequest) GetMediaIds() []string {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *BatchGetMediaURLsRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

type BatchGetMediaURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          map[string]string      `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // media_id -> presigned URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMediaURLsResponse) Reset() {
	*x = BatchGetMediaURLsResponse{}
	mi := &file_media_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMediaURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMediaURLsResponse) ProtoMessage() {}

func (x *BatchGetMediaURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMediaURLsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetMediaURLsResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetMediaURLsResponse) GetUrls() map[string]string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_media_media_proto protoreflect.FileDescriptor

const file_media_media_proto_rawDesc = "" +
	"\n" +
	"\x11media/media.proto\x12\x05media\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\":\n" +
	"\x10GetMediaResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaInfoR\x05media\"\xac\x02\n" +
	"\tMediaInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\x12#\n" +
	"\roriginal_name\x18\b \x01(\tR\foriginalName\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"s\n" +
	"\x18LinkMediaToEntityRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\"5\n" +
	"\x19LinkMediaToEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x18BatchGetMediaURLsRequest\x12\x1b\n" +
	"\tmedia_ids\x18\x01 \x03(\tR\bmediaIds\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\"\x94\x01\n" +
	"\x19BatchGetMediaURLsResponse\x12>\n" +
	"\x04urls\x18\x01 \x03(\v2*.media.BatchGetMediaURLsResponse.UrlsEntryR\x04urls\x1a7\n" +
	"\tUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xfb\x01\n" +
	"\fMediaService\x12;\n" +
	"\bGetMedia\x12\x16.media.GetMediaRequest\x1a\x17.media.GetMediaResponse\x12V\n" +
	"\x11LinkMediaToEntity\x12\x1f.media.LinkMediaToEntityRequest\x1a .media.LinkMediaToEntityResponse\x12V\n" +
	"\x11BatchGetMediaURLs\x12\x1f.media.BatchGetMediaURLsRequest\x1a .media.BatchGetMediaURLsResponseB9Z7github.com/moera-sudo/backend/backend/proto/media;mediab\x06proto3"

var (
	file_media_media_proto_rawDescOnce sync.Once
	file_media_media_proto_rawDescData []byte
)

func file_media_media_proto_rawDescGZIP() []byte {
	file_media_media_proto_rawDescOnce.Do(func() {
		file_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)))
	})
	return file_media_media_proto_rawDescData
}

var file_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_media_media_proto_goTypes = []any{
	(*GetMediaRequest)(nil),           // 0: media.GetMediaRequest
	(*GetMediaResponse)(nil),          // 1: media.GetMediaResponse
	(*MediaInfo)(nil),                 // 2: media.MediaInfo
	(*LinkMediaToEntityRequest)(nil),  // 3: media.LinkMediaToEntityRequest
	(*LinkMediaToEntityResponse)(nil), // 4: media.LinkMediaToEntityResponse
	(*BatchGetMediaURLsRequest)(nil),  // 5: media.BatchGetMediaURLsRequest
	(*BatchGetMediaURLsResponse)(nil), // 6: media.BatchGetMediaURLsResponse
	nil,                               // 7: media.BatchGetMediaURLsResponse.UrlsEntry
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_media_media_proto_depIdxs = []int32{
	2, // 0: media.GetMediaResponse.media:type_name -> media.MediaInfo
	8, // 1: media.MediaInfo.created_at:type_name -> google.protobuf.Timestamp
	7, // 2: media.BatchGetMediaURLsResponse.urls:type_name -> media.BatchGetMediaURLsResponse.UrlsEntry
	0, // 3: media.MediaService.GetMedia:input_type -> media.GetMediaRequest
	3, // 4: media.MediaService.LinkMediaToEntity:input_type -> media.LinkMediaToEntityRequest
	5, // 5: media.MediaService.BatchGetMediaURLs:input_type -> media.BatchGetMediaURLsRequest
	1, // 6: media.MediaService.GetMedia:output_type -> media.GetMediaResponse
	4, // 7: media.MediaService.LinkMediaToEntity:output_type -> media.LinkMediaToEntityResponse
	6, // 8: media.MediaService.BatchGetMediaURLs:output_type -> media.BatchGetMediaURLsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_media_media_proto_init() }
func file_media_media_proto_init() {
	if File_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_media_proto_goTypes,
		DependencyIndexes: file_media_media_proto_depIdxs,
		MessageInfos:      file_media_media_proto_msgTypes,
	}.Build()
	File_media_media_proto = out.File
	file_media_media_proto_goTypes = nil
	file_media_media_proto_depIdxs = nil
}
