info:
  name: Update Settings
  type: http
  seq: 5

http:
  method: PUT
  url: "{{base_url}}{{messenger_prefix}}/channels/{{test_channel_id}}/settings"
  body:
    type: json
    data: |-
      {
        "description": "Updated channel description",
        "is_private": false
      }
  auth:
    type: bearer
    token: "{{access_token}}"

runtime:
  scripts:
    - type: tests
      code: |-
        test("Status is 200", function() {
          expect(res.getStatus()).to.equal(200);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
