// Package media Code generated by swaggo/swag. DO NOT EDIT
package media

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/media/upload/init": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Initialize a file upload and get presigned URL",
                "parameters": [
                    {
                        "description": "Upload parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_domain_models.InitUploadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_domain_models.InitUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/media/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Get media file metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_domain_models.MediaMetadata"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Delete a media file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/media/{id}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Confirm that file was uploaded to S3",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_domain_models.ConfirmUploadResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/media/{id}/download-url": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Get a presigned URL for downloading",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_domain_models.GetURLResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/media/{id}/link": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Link media to an entity (message, chat avatar, etc.)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "entity_type and entity_id",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.MessageRespond"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/media/{id}/url": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Get a presigned URL for inline viewing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Media ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_domain_models.GetURLResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_moera-sudo_backend_backend_media-service_internal_domain_models.ConfirmUploadResponse": {
            "type": "object",
            "properties": {
                "media_id": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_moera-sudo_backend_backend_media-service_internal_domain_models.GetURLResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "media_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_moera-sudo_backend_backend_media-service_internal_domain_models.InitUploadRequest": {
            "type": "object",
            "required": [
                "content_type",
                "kind"
            ],
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "is_private": {
                    "type": "boolean"
                },
                "kind": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "owner_user_id": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "github_com_moera-sudo_backend_backend_media-service_internal_domain_models.InitUploadResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "media_id": {
                    "type": "string"
                },
                "object_key": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "github_com_moera-sudo_backend_backend_media-service_internal_domain_models.MediaMetadata": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_private": {
                    "type": "boolean"
                },
                "kind": {
                    "type": "string"
                },
                "original_name": {
                    "type": "string"
                },
                "owner_user_id": {
                    "type": "string"
                },
                "ready_at": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_moera-sudo_backend_backend_media-service_internal_pkg_http.MessageRespond": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Suda Media Service API",
	Description:      "REST API for file upload, download and management via S3 presigned URLs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
