// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: transaction_access/service.proto

package transaction_access

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionAccessService_ResolveUsername_FullMethodName        = "/transaction_access.TransactionAccessService/ResolveUsername"
	TransactionAccessService_NotifyUserEvent_FullMethodName        = "/transaction_access.TransactionAccessService/NotifyUserEvent"
	TransactionAccessService_CheckChannelPermission_FullMethodName = "/transaction_access.TransactionAccessService/CheckChannelPermission"
	TransactionAccessService_CheckChatMembership_FullMethodName    = "/transaction_access.TransactionAccessService/CheckChatMembership"
	TransactionAccessService_GetUsersByIDs_FullMethodName          = "/transaction_access.TransactionAccessService/GetUsersByIDs"
)

// TransactionAccessServiceClient is the client API for TransactionAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionAccessServiceClient interface {
	// Резолвит username в user_id + EVM address (если у юзера есть кошелёк).
	ResolveUsername(ctx context.Context, in *ResolveUsernameRequest, opts ...grpc.CallOption) (*ResolveUsernameResponse, error)
	// Уведомить юзера о событии. Слитный метод: один вызов делает
	// и WS-нотификацию, и (опционально) system message в чате.
	NotifyUserEvent(ctx context.Context, in *NotifyUserEventRequest, opts ...grpc.CallOption) (*NotifyUserEventResponse, error)
	// Проверка прав юзера в канале (для управления treasury канала).
	CheckChannelPermission(ctx context.Context, in *ChannelPermissionRequest, opts ...grpc.CallOption) (*ChannelPermissionResponse, error)
	// Проверка членства группы юзеров в чате.
	//
	// Используется в transaction-service перед broadcast'ом transfer-in-chat,
	// чтобы убедиться что и отправитель, и получатель — участники этого чата.
	// Возвращает результат для каждого user_id, чтобы вызывающий мог отличить
	// «отправитель не в чате» от «получатель не в чате».
	CheckChatMembership(ctx context.Context, in *ChatMembershipRequest, opts ...grpc.CallOption) (*ChatMembershipResponse, error)
	// Batch-резолв user_id → username + display_name.
	//
	// Используется в transaction-service для treasury-статистики канала:
	// top-донатеры и список донатов хранят только from_user_id, а UI нужны
	// username'ы. Несуществующие id просто отсутствуют в ответе.
	GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*GetUsersByIDsResponse, error)
}

type transactionAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionAccessServiceClient(cc grpc.ClientConnInterface) TransactionAccessServiceClient {
	return &transactionAccessServiceClient{cc}
}

func (c *transactionAccessServiceClient) ResolveUsername(ctx context.Context, in *ResolveUsernameRequest, opts ...grpc.CallOption) (*ResolveUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveUsernameResponse)
	err := c.cc.Invoke(ctx, TransactionAccessService_ResolveUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionAccessServiceClient) NotifyUserEvent(ctx context.Context, in *NotifyUserEventRequest, opts ...grpc.CallOption) (*NotifyUserEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyUserEventResponse)
	err := c.cc.Invoke(ctx, TransactionAccessService_NotifyUserEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionAccessServiceClient) CheckChannelPermission(ctx context.Context, in *ChannelPermissionRequest, opts ...grpc.CallOption) (*ChannelPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelPermissionResponse)
	err := c.cc.Invoke(ctx, TransactionAccessService_CheckChannelPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionAccessServiceClient) CheckChatMembership(ctx context.Context, in *ChatMembershipRequest, opts ...grpc.CallOption) (*ChatMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMembershipResponse)
	err := c.cc.Invoke(ctx, TransactionAccessService_CheckChatMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionAccessServiceClient) GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*GetUsersByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersByIDsResponse)
	err := c.cc.Invoke(ctx, TransactionAccessService_GetUsersByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionAccessServiceServer is the server API for TransactionAccessService service.
// All implementations must embed UnimplementedTransactionAccessServiceServer
// for forward compatibility.
type TransactionAccessServiceServer interface {
	// Резолвит username в user_id + EVM address (если у юзера есть кошелёк).
	ResolveUsername(context.Context, *ResolveUsernameRequest) (*ResolveUsernameResponse, error)
	// Уведомить юзера о событии. Слитный метод: один вызов делает
	// и WS-нотификацию, и (опционально) system message в чате.
	NotifyUserEvent(context.Context, *NotifyUserEventRequest) (*NotifyUserEventResponse, error)
	// Проверка прав юзера в канале (для управления treasury канала).
	CheckChannelPermission(context.Context, *ChannelPermissionRequest) (*ChannelPermissionResponse, error)
	// Проверка членства группы юзеров в чате.
	//
	// Используется в transaction-service перед broadcast'ом transfer-in-chat,
	// чтобы убедиться что и отправитель, и получатель — участники этого чата.
	// Возвращает результат для каждого user_id, чтобы вызывающий мог отличить
	// «отправитель не в чате» от «получатель не в чате».
	CheckChatMembership(context.Context, *ChatMembershipRequest) (*ChatMembershipResponse, error)
	// Batch-резолв user_id → username + display_name.
	//
	// Используется в transaction-service для treasury-статистики канала:
	// top-донатеры и список донатов хранят только from_user_id, а UI нужны
	// username'ы. Несуществующие id просто отсутствуют в ответе.
	GetUsersByIDs(context.Context, *GetUsersByIDsRequest) (*GetUsersByIDsResponse, error)
	mustEmbedUnimplementedTransactionAccessServiceServer()
}

// UnimplementedTransactionAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionAccessServiceServer struct{}

func (UnimplementedTransactionAccessServiceServer) ResolveUsername(context.Context, *ResolveUsernameRequest) (*ResolveUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveUsername not implemented")
}
func (UnimplementedTransactionAccessServiceServer) NotifyUserEvent(context.Context, *NotifyUserEventRequest) (*NotifyUserEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyUserEvent not implemented")
}
func (UnimplementedTransactionAccessServiceServer) CheckChannelPermission(context.Context, *ChannelPermissionRequest) (*ChannelPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckChannelPermission not implemented")
}
func (UnimplementedTransactionAccessServiceServer) CheckChatMembership(context.Context, *ChatMembershipRequest) (*ChatMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckChatMembership not implemented")
}
func (UnimplementedTransactionAccessServiceServer) GetUsersByIDs(context.Context, *GetUsersByIDsRequest) (*GetUsersByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersByIDs not implemented")
}
func (UnimplementedTransactionAccessServiceServer) mustEmbedUnimplementedTransactionAccessServiceServer() {
}
func (UnimplementedTransactionAccessServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionAccessServiceServer will
// result in compilation errors.
type UnsafeTransactionAccessServiceServer interface {
	mustEmbedUnimplementedTransactionAccessServiceServer()
}

func RegisterTransactionAccessServiceServer(s grpc.ServiceRegistrar, srv TransactionAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionAccessService_ServiceDesc, srv)
}

func _TransactionAccessService_ResolveUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionAccessServiceServer).ResolveUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionAccessService_ResolveUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionAccessServiceServer).ResolveUsername(ctx, req.(*ResolveUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionAccessService_NotifyUserEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyUserEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionAccessServiceServer).NotifyUserEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionAccessService_NotifyUserEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionAccessServiceServer).NotifyUserEvent(ctx, req.(*NotifyUserEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionAccessService_CheckChannelPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionAccessServiceServer).CheckChannelPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionAccessService_CheckChannelPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionAccessServiceServer).CheckChannelPermission(ctx, req.(*ChannelPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionAccessService_CheckChatMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionAccessServiceServer).CheckChatMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionAccessService_CheckChatMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionAccessServiceServer).CheckChatMembership(ctx, req.(*ChatMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionAccessService_GetUsersByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionAccessServiceServer).GetUsersByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionAccessService_GetUsersByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionAccessServiceServer).GetUsersByIDs(ctx, req.(*GetUsersByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionAccessService_ServiceDesc is the grpc.ServiceDesc for TransactionAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction_access.TransactionAccessService",
	HandlerType: (*TransactionAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveUsername",
			Handler:    _TransactionAccessService_ResolveUsername_Handler,
		},
		{
			MethodName: "NotifyUserEvent",
			Handler:    _TransactionAccessService_NotifyUserEvent_Handler,
		},
		{
			MethodName: "CheckChannelPermission",
			Handler:    _TransactionAccessService_CheckChannelPermission_Handler,
		},
		{
			MethodName: "CheckChatMembership",
			Handler:    _TransactionAccessService_CheckChatMembership_Handler,
		},
		{
			MethodName: "GetUsersByIDs",
			Handler:    _TransactionAccessService_GetUsersByIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction_access/service.proto",
}
