// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transaction_access/service.proto

package transaction_access

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // без @, например "john"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUsernameRequest) Reset() {
	*x = ResolveUsernameRequest{}
	mi := &file_transaction_access_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUsernameRequest) ProtoMessage() {}

func (x *ResolveUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUsernameRequest.ProtoReflect.Descriptor instead.
func (*ResolveUsernameRequest) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ResolveUsernameResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Found       bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	UserId      string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // UUID юзера в messenger_users (если found=true)
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // для UI
	// wallet_address пустой, если у юзера ещё нет кошелька в transaction-service.
	// Тогда вызывающий должен либо отказать в операции, либо сначала вызвать
	// CreateWalletForUser (но это противоречит lazy-логике, так что лучше отказать).
	WalletAddress string `protobuf:"bytes,4,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUsernameResponse) Reset() {
	*x = ResolveUsernameResponse{}
	mi := &file_transaction_access_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUsernameResponse) ProtoMessage() {}

func (x *ResolveUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUsernameResponse.ProtoReflect.Descriptor instead.
func (*ResolveUsernameResponse) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveUsernameResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveUsernameResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveUsernameResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResolveUsernameResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

// event_type values (фронт мапит на UI-карточки):
//
//	SUDA_RECEIVED          — входящий перевод SUDA
//	SUDA_SENT              — исходящий перевод (для списка операций)
//	NFT_RECEIVED           — получен NFT (gift или покупка)
//	NFT_SOLD               — твой NFT купили
//	DONATION_RECEIVED      — донат на канал, где ты owner/admin
//	QUEST_CLAIMED          — твой квест взяли (creator получает)
//	QUEST_SUBMITTED        — исполнитель сдал работу
//	QUEST_APPROVED         — квест подтверждён, награда выплачена
//	QUEST_CANCELLED        — квест отменён
//	QUEST_EXPIRED          — дедлайн прошёл, refund
//	FUNDRAISE_CONTRIBUTION — твой сбор получил вклад
//	FUNDRAISE_GOAL_REACHED — цель сбора достигнута
//	FUNDRAISE_EXPIRED      — сбор истёк, можно делать refund
//
// payload_json — JSON-строка, конкретная схема зависит от event_type.
// Примеры:
//
//	SUDA_RECEIVED:       {"from_user_id":"...","from_username":"alice","amount_wei":"100000...","tx_hash":"0x..."}
//	NFT_RECEIVED:        {"from_user_id":"...","nft_item_id":"...","nft_name":"Cool Sticker","media_id":"..."}
//	DONATION_RECEIVED:   {"channel_id":"...","from_user_id":"...","amount_wei":"...","message":"thanks!","tx_hash":"..."}
//	QUEST_APPROVED:      {"quest_id":"...","reward_wei":"500000..."}
type NotifyUserEventRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // получатель уведомления
	EventType   string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// Если указан — Messenger дополнительно создаёт system message
	// в этом чате (типа DONATION/NFT_GIFT/QUEST/FUNDRAISE) с тем же payload.
	// Пусто — только WS-уведомление, без записи в историю чата.
	TargetChatId string `protobuf:"bytes,4,opt,name=target_chat_id,json=targetChatId,proto3" json:"target_chat_id,omitempty"`
	// Тип system message (если target_chat_id указан).
	// Значения соответствуют messenger_messages.type:
	//
	//	DONATION | NFT_GIFT | QUEST | FUNDRAISE
	//
	// Пусто — не создавать system message, даже если target_chat_id есть.
	SystemMessageType string `protobuf:"bytes,5,opt,name=system_message_type,json=systemMessageType,proto3" json:"system_message_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotifyUserEventRequest) Reset() {
	*x = NotifyUserEventRequest{}
	mi := &file_transaction_access_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyUserEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUserEventRequest) ProtoMessage() {}

func (x *NotifyUserEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUserEventRequest.ProtoReflect.Descriptor instead.
func (*NotifyUserEventRequest) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyUserEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyUserEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *NotifyUserEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *NotifyUserEventRequest) GetTargetChatId() string {
	if x != nil {
		return x.TargetChatId
	}
	return ""
}

func (x *NotifyUserEventRequest) GetSystemMessageType() string {
	if x != nil {
		return x.SystemMessageType
	}
	return ""
}

type NotifyUserEventResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WsDelivered     bool                   `protobuf:"varint,1,opt,name=ws_delivered,json=wsDelivered,proto3" json:"ws_delivered,omitempty"`              // true если юзер был онлайн и WS отправлен
	MessageCreated  bool                   `protobuf:"varint,2,opt,name=message_created,json=messageCreated,proto3" json:"message_created,omitempty"`     // true если был создан system message
	SystemMessageId string                 `protobuf:"bytes,3,opt,name=system_message_id,json=systemMessageId,proto3" json:"system_message_id,omitempty"` // id созданного сообщения (если был создан)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotifyUserEventResponse) Reset() {
	*x = NotifyUserEventResponse{}
	mi := &file_transaction_access_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyUserEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUserEventResponse) ProtoMessage() {}

func (x *NotifyUserEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUserEventResponse.ProtoReflect.Descriptor instead.
func (*NotifyUserEventResponse) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyUserEventResponse) GetWsDelivered() bool {
	if x != nil {
		return x.WsDelivered
	}
	return false
}

func (x *NotifyUserEventResponse) GetMessageCreated() bool {
	if x != nil {
		return x.MessageCreated
	}
	return false
}

func (x *NotifyUserEventResponse) GetSystemMessageId() string {
	if x != nil {
		return x.SystemMessageId
	}
	return ""
}

// permission values:
//
//	OWNER          — только владелец канала
//	OWNER_OR_ADMIN — владелец или один из админов
//	MEMBER         — любой участник (для квестов: создавать может только админ,
//	                 но claim'ить может любой подписчик канала)
type ChannelPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelPermissionRequest) Reset() {
	*x = ChannelPermissionRequest{}
	mi := &file_transaction_access_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPermissionRequest) ProtoMessage() {}

func (x *ChannelPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPermissionRequest.ProtoReflect.Descriptor instead.
func (*ChannelPermissionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChannelPermissionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type ChannelPermissionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Granted bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	// reason: "ok" | "not_a_member" | "not_admin" | "not_owner" | "channel_not_found"
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelPermissionResponse) Reset() {
	*x = ChannelPermissionResponse{}
	mi := &file_transaction_access_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPermissionResponse) ProtoMessage() {}

func (x *ChannelPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPermissionResponse.ProtoReflect.Descriptor instead.
func (*ChannelPermissionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelPermissionResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *ChannelPermissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChatMembershipRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ChatId string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Массив user_id для проверки в одном запросе.
	// Используется например для transfer-in-chat: один вызов проверяет
	// что и отправитель, и получатель — члены чата.
	UserIds       []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMembershipRequest) Reset() {
	*x = ChatMembershipRequest{}
	mi := &file_transaction_access_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMembershipRequest) ProtoMessage() {}

func (x *ChatMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMembershipRequest.ProtoReflect.Descriptor instead.
func (*ChatMembershipRequest) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMembershipRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMembershipRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ChatMembershipResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chat_exists=false → чата нет, все members=false.
	ChatExists bool `protobuf:"varint,1,opt,name=chat_exists,json=chatExists,proto3" json:"chat_exists,omitempty"`
	// Результаты в том же порядке, что user_ids в запросе.
	// members[i].is_member соответствует user_ids[i].
	Members       []*UserMembership `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMembershipResponse) Reset() {
	*x = ChatMembershipResponse{}
	mi := &file_transaction_access_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMembershipResponse) ProtoMessage() {}

func (x *ChatMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMembershipResponse.ProtoReflect.Descriptor instead.
func (*ChatMembershipResponse) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMembershipResponse) GetChatExists() bool {
	if x != nil {
		return x.ChatExists
	}
	return false
}

func (x *ChatMembershipResponse) GetMembers() []*UserMembership {
	if x != nil {
		return x.Members
	}
	return nil
}

type UserMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsMember      bool                   `protobuf:"varint,2,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // если is_member=true: OWNER | ADMIN | MEMBER | SUBSCRIBER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMembership) Reset() {
	*x = UserMembership{}
	mi := &file_transaction_access_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMembership) ProtoMessage() {}

func (x *UserMembership) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMembership.ProtoReflect.Descriptor instead.
func (*UserMembership) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{8}
}

func (x *UserMembership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMembership) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *UserMembership) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetUsersByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsRequest) Reset() {
	*x = GetUsersByIDsRequest{}
	mi := &file_transaction_access_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsRequest) ProtoMessage() {}

func (x *GetUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetUsersByIDsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersByIDsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Только найденные юзеры. Порядок не гарантирован, маппить по user_id.
	Users         []*UserBrief `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsResponse) Reset() {
	*x = GetUsersByIDsResponse{}
	mi := &file_transaction_access_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsResponse) ProtoMessage() {}

func (x *GetUsersByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUsersByIDsResponse) GetUsers() []*UserBrief {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_transaction_access_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_access_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_transaction_access_service_proto_rawDescGZIP(), []int{11}
}

func (x *UserBrief) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBrief) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserBrief) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_transaction_access_service_proto protoreflect.FileDescriptor

const file_transaction_access_service_proto_rawDesc = "" +
	"\n" +
	" transaction_access/service.proto\x12\x12transaction_access\"4\n" +
	"\x16ResolveUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x92\x01\n" +
	"\x17ResolveUsernameResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12%\n" +
	"\x0ewallet_address\x18\x04 \x01(\tR\rwalletAddress\"\xc9\x01\n" +
	"\x16NotifyUserEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\x12$\n" +
	"\x0etarget_chat_id\x18\x04 \x01(\tR\ftargetChatId\x12.\n" +
	"\x13system_message_type\x18\x05 \x01(\tR\x11systemMessageType\"\x91\x01\n" +
	"\x17NotifyUserEventResponse\x12!\n" +
	"\fws_delivered\x18\x01 \x01(\bR\vwsDelivered\x12'\n" +
	"\x0fmessage_created\x18\x02 \x01(\bR\x0emessageCreated\x12*\n" +
	"\x11system_message_id\x18\x03 \x01(\tR\x0fsystemMessageId\"r\n" +
	"\x18ChannelPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"M\n" +
	"\x19ChannelPermissionResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x15ChatMembershipRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"w\n" +
	"\x16ChatMembershipResponse\x12\x1f\n" +
	"\vchat_exists\x18\x01 \x01(\bR\n" +
	"chatExists\x12<\n" +
	"\amembers\x18\x02 \x03(\v2\".transaction_access.UserMembershipR\amembers\"Z\n" +
	"\x0eUserMembership\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_member\x18\x02 \x01(\bR\bisMember\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"1\n" +
	"\x14GetUsersByIDsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"L\n" +
	"\x15GetUsersByIDsResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.transaction_access.UserBriefR\x05users\"c\n" +
	"\tUserBrief\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName2\xbd\x04\n" +
	"\x18TransactionAccessService\x12j\n" +
	"\x0fResolveUsername\x12*.transaction_access.ResolveUsernameRequest\x1a+.transaction_access.ResolveUsernameResponse\x12j\n" +
	"\x0fNotifyUserEvent\x12*.transaction_access.NotifyUserEventRequest\x1a+.transaction_access.NotifyUserEventResponse\x12u\n" +
	"\x16CheckChannelPermission\x12,.transaction_access.ChannelPermissionRequest\x1a-.transaction_access.ChannelPermissionResponse\x12l\n" +
	"\x13CheckChatMembership\x12).transaction_access.ChatMembershipRequest\x1a*.transaction_access.ChatMembershipResponse\x12d\n" +
	"\rGetUsersByIDs\x12(.transaction_access.GetUsersByIDsRequest\x1a).transaction_access.GetUsersByIDsResponseBSZQgithub.com/moera-sudo/backend/backend/proto/transaction_access;transaction_accessb\x06proto3"

var (
	file_transaction_access_service_proto_rawDescOnce sync.Once
	file_transaction_access_service_proto_rawDescData []byte
)

func file_transaction_access_service_proto_rawDescGZIP() []byte {
	file_transaction_access_service_proto_rawDescOnce.Do(func() {
		file_transaction_access_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_access_service_proto_rawDesc), len(file_transaction_access_service_proto_rawDesc)))
	})
	return file_transaction_access_service_proto_rawDescData
}

var file_transaction_access_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transaction_access_service_proto_goTypes = []any{
	(*ResolveUsernameRequest)(nil),    // 0: transaction_access.ResolveUsernameRequest
	(*ResolveUsernameResponse)(nil),   // 1: transaction_access.ResolveUsernameResponse
	(*NotifyUserEventRequest)(nil),    // 2: transaction_access.NotifyUserEventRequest
	(*NotifyUserEventResponse)(nil),   // 3: transaction_access.NotifyUserEventResponse
	(*ChannelPermissionRequest)(nil),  // 4: transaction_access.ChannelPermissionRequest
	(*ChannelPermissionResponse)(nil), // 5: transaction_access.ChannelPermissionResponse
	(*ChatMembershipRequest)(nil),     // 6: transaction_access.ChatMembershipRequest
	(*ChatMembershipResponse)(nil),    // 7: transaction_access.ChatMembershipResponse
	(*UserMembership)(nil),            // 8: transaction_access.UserMembership
	(*GetUsersByIDsRequest)(nil),      // 9: transaction_access.GetUsersByIDsRequest
	(*GetUsersByIDsResponse)(nil),     // 10: transaction_access.GetUsersByIDsResponse
	(*UserBrief)(nil),                 // 11: transaction_access.UserBrief
}
var file_transaction_access_service_proto_depIdxs = []int32{
	8,  // 0: transaction_access.ChatMembershipResponse.members:type_name -> transaction_access.UserMembership
	11, // 1: transaction_access.GetUsersByIDsResponse.users:type_name -> transaction_access.UserBrief
	0,  // 2: transaction_access.TransactionAccessService.ResolveUsername:input_type -> transaction_access.ResolveUsernameRequest
	2,  // 3: transaction_access.TransactionAccessService.NotifyUserEvent:input_type -> transaction_access.NotifyUserEventRequest
	4,  // 4: transaction_access.TransactionAccessService.CheckChannelPermission:input_type -> transaction_access.ChannelPermissionRequest
	6,  // 5: transaction_access.TransactionAccessService.CheckChatMembership:input_type -> transaction_access.ChatMembershipRequest
	9,  // 6: transaction_access.TransactionAccessService.GetUsersByIDs:input_type -> transaction_access.GetUsersByIDsRequest
	1,  // 7: transaction_access.TransactionAccessService.ResolveUsername:output_type -> transaction_access.ResolveUsernameResponse
	3,  // 8: transaction_access.TransactionAccessService.NotifyUserEvent:output_type -> transaction_access.NotifyUserEventResponse
	5,  // 9: transaction_access.TransactionAccessService.CheckChannelPermission:output_type -> transaction_access.ChannelPermissionResponse
	7,  // 10: transaction_access.TransactionAccessService.CheckChatMembership:output_type -> transaction_access.ChatMembershipResponse
	10, // 11: transaction_access.TransactionAccessService.GetUsersByIDs:output_type -> transaction_access.GetUsersByIDsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_access_service_proto_init() }
func file_transaction_access_service_proto_init() {
	if File_transaction_access_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_access_service_proto_rawDesc), len(file_transaction_access_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_access_service_proto_goTypes,
		DependencyIndexes: file_transaction_access_service_proto_depIdxs,
		MessageInfos:      file_transaction_access_service_proto_msgTypes,
	}.Build()
	File_transaction_access_service_proto = out.File
	file_transaction_access_service_proto_goTypes = nil
	file_transaction_access_service_proto_depIdxs = nil
}
