// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: messenger_access/messenger_access.proto

package messenger_access

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessengerAccessService_CheckEntityAccess_FullMethodName = "/messenger_access.MessengerAccessService/CheckEntityAccess"
)

// MessengerAccessServiceClient is the client API for MessengerAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===================================================
// Messenger Access Service
// Реализуется в messenger-service.
// Вызывается из media-service для проверки доступа к приватным файлам.
//
// Flow:
//  1. Клиент -> media-service: GET /api/media/:id/url
//  2. media-service видит is_private=true, находит entity_link (MESSAGE, msg_id)
//  3. media-service -> messenger-service: CheckEntityAccess(user_id, MESSAGE, msg_id)
//  4. messenger-service: msg_id -> chat_id -> проверяет chat_members
//  5. Возвращает has_access = true/false
//
// ===================================================
type MessengerAccessServiceClient interface {
	CheckEntityAccess(ctx context.Context, in *CheckEntityAccessRequest, opts ...grpc.CallOption) (*CheckEntityAccessResponse, error)
}

type messengerAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessengerAccessServiceClient(cc grpc.ClientConnInterface) MessengerAccessServiceClient {
	return &messengerAccessServiceClient{cc}
}

func (c *messengerAccessServiceClient) CheckEntityAccess(ctx context.Context, in *CheckEntityAccessRequest, opts ...grpc.CallOption) (*CheckEntityAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEntityAccessResponse)
	err := c.cc.Invoke(ctx, MessengerAccessService_CheckEntityAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessengerAccessServiceServer is the server API for MessengerAccessService service.
// All implementations must embed UnimplementedMessengerAccessServiceServer
// for forward compatibility.
//
// ===================================================
// Messenger Access Service
// Реализуется в messenger-service.
// Вызывается из media-service для проверки доступа к приватным файлам.
//
// Flow:
//  1. Клиент -> media-service: GET /api/media/:id/url
//  2. media-service видит is_private=true, находит entity_link (MESSAGE, msg_id)
//  3. media-service -> messenger-service: CheckEntityAccess(user_id, MESSAGE, msg_id)
//  4. messenger-service: msg_id -> chat_id -> проверяет chat_members
//  5. Возвращает has_access = true/false
//
// ===================================================
type MessengerAccessServiceServer interface {
	CheckEntityAccess(context.Context, *CheckEntityAccessRequest) (*CheckEntityAccessResponse, error)
	mustEmbedUnimplementedMessengerAccessServiceServer()
}

// UnimplementedMessengerAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessengerAccessServiceServer struct{}

func (UnimplementedMessengerAccessServiceServer) CheckEntityAccess(context.Context, *CheckEntityAccessRequest) (*CheckEntityAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEntityAccess not implemented")
}
func (UnimplementedMessengerAccessServiceServer) mustEmbedUnimplementedMessengerAccessServiceServer() {
}
func (UnimplementedMessengerAccessServiceServer) testEmbeddedByValue() {}

// UnsafeMessengerAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessengerAccessServiceServer will
// result in compilation errors.
type UnsafeMessengerAccessServiceServer interface {
	mustEmbedUnimplementedMessengerAccessServiceServer()
}

func RegisterMessengerAccessServiceServer(s grpc.ServiceRegistrar, srv MessengerAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedMessengerAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessengerAccessService_ServiceDesc, srv)
}

func _MessengerAccessService_CheckEntityAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEntityAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerAccessServiceServer).CheckEntityAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessengerAccessService_CheckEntityAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerAccessServiceServer).CheckEntityAccess(ctx, req.(*CheckEntityAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessengerAccessService_ServiceDesc is the grpc.ServiceDesc for MessengerAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessengerAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messenger_access.MessengerAccessService",
	HandlerType: (*MessengerAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckEntityAccess",
			Handler:    _MessengerAccessService_CheckEntityAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messenger_access/messenger_access.proto",
}
