// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: messenger_access/messenger_access.proto

package messenger_access

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckEntityAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // MESSAGE, CHAT_AVATAR
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`       // message_id, chat_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEntityAccessRequest) Reset() {
	*x = CheckEntityAccessRequest{}
	mi := &file_messenger_access_messenger_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEntityAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEntityAccessRequest) ProtoMessage() {}

func (x *CheckEntityAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_access_messenger_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEntityAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckEntityAccessRequest) Descriptor() ([]byte, []int) {
	return file_messenger_access_messenger_access_proto_rawDescGZIP(), []int{0}
}

func (x *CheckEntityAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckEntityAccessRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CheckEntityAccessRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type CheckEntityAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "not_a_member", "chat_not_found", "message_not_found"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckEntityAccessResponse) Reset() {
	*x = CheckEntityAccessResponse{}
	mi := &file_messenger_access_messenger_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckEntityAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEntityAccessResponse) ProtoMessage() {}

func (x *CheckEntityAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_access_messenger_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEntityAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckEntityAccessResponse) Descriptor() ([]byte, []int) {
	return file_messenger_access_messenger_access_proto_rawDescGZIP(), []int{1}
}

func (x *CheckEntityAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *CheckEntityAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_messenger_access_messenger_access_proto protoreflect.FileDescriptor

const file_messenger_access_messenger_access_proto_rawDesc = "" +
	"\n" +
	"'messenger_access/messenger_access.proto\x12\x10messenger_access\"q\n" +
	"\x18CheckEntityAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\"R\n" +
	"\x19CheckEntityAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x86\x01\n" +
	"\x16MessengerAccessService\x12l\n" +
	"\x11CheckEntityAccess\x12*.messenger_access.CheckEntityAccessRequest\x1a+.messenger_access.CheckEntityAccessResponseBOZMgithub.com/moera-sudo/backend/backend/proto/messenger_access;messenger_accessb\x06proto3"

var (
	file_messenger_access_messenger_access_proto_rawDescOnce sync.Once
	file_messenger_access_messenger_access_proto_rawDescData []byte
)

func file_messenger_access_messenger_access_proto_rawDescGZIP() []byte {
	file_messenger_access_messenger_access_proto_rawDescOnce.Do(func() {
		file_messenger_access_messenger_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_access_messenger_access_proto_rawDesc), len(file_messenger_access_messenger_access_proto_rawDesc)))
	})
	return file_messenger_access_messenger_access_proto_rawDescData
}

var file_messenger_access_messenger_access_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messenger_access_messenger_access_proto_goTypes = []any{
	(*CheckEntityAccessRequest)(nil),  // 0: messenger_access.CheckEntityAccessRequest
	(*CheckEntityAccessResponse)(nil), // 1: messenger_access.CheckEntityAccessResponse
}
var file_messenger_access_messenger_access_proto_depIdxs = []int32{
	0, // 0: messenger_access.MessengerAccessService.CheckEntityAccess:input_type -> messenger_access.CheckEntityAccessRequest
	1, // 1: messenger_access.MessengerAccessService.CheckEntityAccess:output_type -> messenger_access.CheckEntityAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messenger_access_messenger_access_proto_init() }
func file_messenger_access_messenger_access_proto_init() {
	if File_messenger_access_messenger_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_access_messenger_access_proto_rawDesc), len(file_messenger_access_messenger_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messenger_access_messenger_access_proto_goTypes,
		DependencyIndexes: file_messenger_access_messenger_access_proto_depIdxs,
		MessageInfos:      file_messenger_access_messenger_access_proto_msgTypes,
	}.Build()
	File_messenger_access_messenger_access_proto = out.File
	file_messenger_access_messenger_access_proto_goTypes = nil
	file_messenger_access_messenger_access_proto_depIdxs = nil
}
